# CMake generated Testfile for 
# Source directory: C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing
# Build directory: C:/Project/PlusB-bin/PlusLib-bin/src/PlusImageProcessing/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkPlusTransverseProcessEnhancerTest "C:/Project/PlusB-bin/bin/vtkPlusTransverseProcessEnhancerTest" "--input-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/PlusTransverseProcessEnhancerTestData.igs.mha" "--output-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/outputPlusTransverseProcessEnhancerTest.igs.mha" "--input-config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusTransverseProcessEnhancerTestingParameters.xml" "--save-intermediate-images=false")
set_tests_properties(vtkPlusTransverseProcessEnhancerTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;13;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusRfToBrightnessConvertRunTest "C:/Project/PlusB-bin/bin/RfProcessor" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_RfProcessingAlgoCurvilinearTest.xml" "--rf-file=C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixCurvilinearRfData.igs.mha" "--output-img-file=outputUltrasonixCurvilinearBrightnessData.igs.mha" "--use-compression=false" "--operation=BRIGHTNESS_CONVERT")
set_tests_properties(vtkPlusRfToBrightnessConvertRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;24;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusRfToBrightnessConvertCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/Project/PlusB-bin/bin/Release/Output/outputUltrasonixCurvilinearBrightnessData_OutputChannel_ScanConvertOutput.igs.mha" "C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixCurvilinearBrightnessData.igs.mha")
set_tests_properties(vtkPlusRfToBrightnessConvertCompareToBaselineTest PROPERTIES  DEPENDS "vtkPlusRfToBrightnessConvertRunTest" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;34;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertCurvilinearRunTest "C:/Project/PlusB-bin/bin/RfProcessor" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_RfProcessingAlgoCurvilinearTest.xml" "--rf-file=C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixCurvilinearRfData.igs.mha" "--output-img-file=outputUltrasonixCurvilinearScanConvertedData.igs.mha" "--use-compression=false" "--operation=BRIGHTNESS_SCAN_CONVERT")
set_tests_properties(vtkPlusUsScanConvertCurvilinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;42;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertCurvilinearCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/Project/PlusB-bin/bin/Release/Output/outputUltrasonixCurvilinearScanConvertedData_OutputChannel_ScanConvertOutput.igs.mha" "C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixCurvilinearScanConvertedData.igs.mha")
set_tests_properties(vtkPlusUsScanConvertCurvilinearCompareToBaselineTest PROPERTIES  DEPENDS "vtkPlusUsScanConvertCurvilinearRunTest" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;52;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertLinearRunTest "C:/Project/PlusB-bin/bin/RfProcessor" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_RfProcessingAlgoLinearTest.xml" "--rf-file=C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixLinearRfData.igs.mha" "--output-img-file=outputUltrasonixLinearScanConvertedData.igs.mha" "--operation=BRIGHTNESS_SCAN_CONVERT" "--use-compression=false")
set_tests_properties(vtkPlusUsScanConvertLinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;60;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertLinearCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/Project/PlusB-bin/bin/Release/Output/outputUltrasonixLinearScanConvertedData_OutputChannel_ScanConvertOutput.igs.mha" "C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixLinearScanConvertedData.igs.mha")
set_tests_properties(vtkPlusUsScanConvertLinearCompareToBaselineTest PROPERTIES  DEPENDS "vtkPlusUsScanConvertLinearRunTest" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;70;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertBkCurvilinearRunTest "C:/Project/PlusB-bin/bin/RfProcessor" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/PlusDeviceSet_fCal_BkProFocus_OpenIGTLinkTracker.xml" "--rf-file=C:/Project/PlusB-bin/PlusLibData/TestImages/BkCurvilinearRfData.igs.mhd" "--output-img-file=outputBkCurvilinearScanConvertedData.igs.mha" "--operation=BRIGHTNESS_SCAN_CONVERT" "--use-compression=false")
set_tests_properties(vtkPlusUsScanConvertBkCurvilinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;78;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(vtkPlusUsScanConvertBkCurvilinearCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/Project/PlusB-bin/bin/Release/Output/outputBkCurvilinearScanConvertedData_OutputChannel_VideoStream.igs.mha" "C:/Project/PlusB-bin/PlusLibData/TestImages/BkCurvilinearScanConvertedData.igs.mha")
set_tests_properties(vtkPlusUsScanConvertBkCurvilinearCompareToBaselineTest PROPERTIES  DEPENDS "vtkPlusUsScanConvertBkCurvilinearRunTest" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;88;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(DrawScanLinesCurvilinearRunTest "C:/Project/PlusB-bin/bin/DrawScanLines" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_RfProcessingAlgoCurvilinearTest.xml" "--source-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixCurvilinearScanConvertedData.igs.mha" "--output-seq-file=UltrasonixCurvilinearScanConvertedDataWithScanlines.igs.mha")
set_tests_properties(DrawScanLinesCurvilinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;96;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(DrawScanLinesLinearRunTest "C:/Project/PlusB-bin/bin/DrawScanLines" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_RfProcessingAlgoLinearTest.xml" "--source-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/UltrasonixLinearScanConvertedData.igs.mha" "--output-seq-file=UltrasonixLinearScanConvertedDataWithScanlines.igs.mha")
set_tests_properties(DrawScanLinesLinearRunTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;105;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(ExtractScanLinesCurvilinearRunTest "C:/Project/PlusB-bin/bin/ExtractScanLines" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/SpineUltrasound-Lumbar-C5_config.xml" "--input-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/SpineUltrasound-Lumbar-C5.igs.mha" "--output-seq-file=SpineUltrasound-Lumbar-C5_ScanLines.igs.mha")
set_tests_properties(ExtractScanLinesCurvilinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;114;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
add_test(ExtractScanLinesLinearRunTest "C:/Project/PlusB-bin/bin/ExtractScanLines" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/BoneUltrasound_L14_config.xml" "--input-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/BoneUltrasound_L14.igs.mha" "--output-seq-file=BoneUltrasound_L14_ScanLines.igs.mha")
set_tests_properties(ExtractScanLinesLinearRunTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;123;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusImageProcessing/Testing/CMakeLists.txt;0;")
