/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkPlusHapticsExport - manage Windows system differences
// .SECTION Description
// The __vtkPlusHapticsExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkPlusHapticsExport_h
#define __vtkPlusHapticsExport_h

#if defined(WIN32) && !defined(PlusLib_STATIC)
 #if defined(vtkPlusHaptics_EXPORTS)
  #define vtkPlusHapticsExport __declspec( dllexport )
 #else
  #define vtkPlusHapticsExport __declspec( dllimport )
 #endif
#else
 #define vtkPlusHapticsExport
#endif

#endif
