# Install script for directory: C:/Project/PlusB-bin/itk

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Project/PlusB-bin/itk-int")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelopmentx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES
    "C:/Project/PlusB-bin/itk-bin/CMakeFiles/ITKConfig.cmake"
    "C:/Project/PlusB-bin/itk-bin/ITKConfigVersion.cmake"
    "C:/Project/PlusB-bin/itk/CMake/ITKModuleAPI.cmake"
    "C:/Project/PlusB-bin/itk/CMake/UseITK.cmake"
    "C:/Project/PlusB-bin/itk/CMake/itkImageIOFactoryRegisterManager.h.in"
    "C:/Project/PlusB-bin/itk/CMake/itkTransformIOFactoryRegisterManager.h.in"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelopmentx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12/ITKTargets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12/ITKTargets.cmake"
         "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12/ITKTargets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12/ITKTargets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/ITK-4.12" TYPE FILE FILES "C:/Project/PlusB-bin/itk-bin/CMakeFiles/Export/lib/cmake/ITK-4.12/ITKTargets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xRuntimex" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/doc/ITK-4.12" TYPE FILE FILES
    "C:/Project/PlusB-bin/itk/LICENSE"
    "C:/Project/PlusB-bin/itk/NOTICE"
    "C:/Project/PlusB-bin/itk/README.txt"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Project/PlusB-bin/itk-bin/Modules/Remote/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/DoubleConversion/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/KWIML/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/KWSys/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/VNL/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/VNLInstantiation/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/Common/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/FiniteDifference/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageFilterBase/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/CurvatureFlow/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/ImageAdaptors/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/Netlib/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/Statistics/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/Transform/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/ImageFunction/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageGrid/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/AnisotropicSmoothing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/LabelMap/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageCompose/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/Mesh/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/ZLIB/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/MetaIO/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/SpatialObjects/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageStatistics/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Path/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageIntensity/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Thresholding/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/ConnectedComponents/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/MathematicalMorphology/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/BinaryMathematicalMorphology/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageLabel/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/NarrowBand/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/DistanceMap/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/QuadEdgeMesh/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/FastMarching/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/ImageBase/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageCompare/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Smoothing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageGradient/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageSources/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageFeature/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/Optimizers/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/SignedDistanceFunction/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/LevelSets/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/AntiAlias/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/Polynomials/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/BiasCorrection/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/BioCell/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/Classifiers/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Colormap/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/FFT/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Convolution/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/DICOMParser/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Deconvolution/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/DeformableMesh/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/Denoising/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/DiffusionTensorImage/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/DisplacementField/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/Eigen/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/Expat/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/XML/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/SpatialObjects/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/Common/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/FEM/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/PDEDeformable/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/FEM/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/GDCM/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/NIFTI/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/GIFTI/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/GPUCommon/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/GPUFiniteDifference/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/GPUAnisotropicSmoothing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/GPUImageFilterBase/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/GPUCommon/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/GPUPDEDeformable/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/GPUSmoothing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/GPUThresholding/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/HDF5/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/BMP/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/BioRad/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/CSV/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/GDCM/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/IPL/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/GE/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/GIPL/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/HDF5/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/JPEG/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/JPEG/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/TIFF/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TIFF/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/LSM/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/MRC/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/Mesh/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/Meta/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/NIFTI/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/NrrdIO/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/NRRD/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/PNG/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/PNG/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/RAW/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/Siemens/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/Stimulate/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TransformFactory/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TransformBase/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TransformHDF5/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TransformInsightLegacy/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/TransformMatlab/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/IO/VTK/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageFusion/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/ImageNoise/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Nonunit/IntegratedTest/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/KLMRegionGrowing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/LabelVoting/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/LevelSetsv4/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/MarkovRandomFieldsClassifiers/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/Optimizersv4/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/Metricsv4/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Numerics/NeuralNetworks/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/OpenJPEG/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/QuadEdgeMeshFiltering/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/RegionGrowing/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Registration/RegistrationMethodsv4/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Filtering/SpatialFunction/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Bridge/VTK/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/Voronoi/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Segmentation/Watersheds/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Nonunit/Review/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Core/TestKernel/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Video/Core/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Video/Filtering/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Modules/Video/IO/cmake_install.cmake")
  include("C:/Project/PlusB-bin/itk-bin/Utilities/Doxygen/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/Project/PlusB-bin/itk-bin/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
