/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkPlusDataCollectionExport - manage Windows system differences
// .SECTION Description
// The __vtkPlusDataCollectionExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkPlusDataCollectionExport_h
#define __vtkPlusDataCollectionExport_h

#if defined(WIN32) && !defined(PlusLib_STATIC)
 #if defined(vtkPlusDataCollection_EXPORTS)
  #define vtkPlusDataCollectionExport __declspec( dllexport )
 #else
  #define vtkPlusDataCollectionExport __declspec( dllimport )
 #endif
#else
 #define vtkPlusDataCollectionExport
#endif

#endif
