
#ifndef OPENIGTLINKIO_DEVICES_EXPORT_H
#define OPENIGTLINKIO_DEVICES_EXPORT_H

#ifdef IGTLIODEVICES_STATIC_DEFINE
#  define OPENIGTLINKIO_DEVICES_EXPORT
#  define IGTLIODEVICES_NO_EXPORT
#else
#  ifndef OPENIGTLINKIO_DEVICES_EXPORT
#    ifdef igtlioDevices_EXPORTS
        /* We are building this library */
#      define OPENIGTLINKIO_DEVICES_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define OPENIGTLINKIO_DEVICES_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef IGTLIODEVICES_NO_EXPORT
#    define IGTLIODEVICES_NO_EXPORT 
#  endif
#endif

#ifndef IGTLIODEVICES_DEPRECATED
#  define IGTLIODEVICES_DEPRECATED __declspec(deprecated)
#endif

#ifndef IGTLIODEVICES_DEPRECATED_EXPORT
#  define IGTLIODEVICES_DEPRECATED_EXPORT OPENIGTLINKIO_DEVICES_EXPORT IGTLIODEVICES_DEPRECATED
#endif

#ifndef IGTLIODEVICES_DEPRECATED_NO_EXPORT
#  define IGTLIODEVICES_DEPRECATED_NO_EXPORT IGTLIODEVICES_NO_EXPORT IGTLIODEVICES_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef IGTLIODEVICES_NO_DEPRECATED
#    define IGTLIODEVICES_NO_DEPRECATED
#  endif
#endif

#endif /* OPENIGTLINKIO_DEVICES_EXPORT_H */
