/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkPlusOpenIGTLinkExport - manage Windows system differences
// .SECTION Description
// The __vtkPlusOpenIGTLinkExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkPlusOpenIGTLinkExport_h
#define __vtkPlusOpenIGTLinkExport_h

#if defined(WIN32) && !defined(PlusLib_STATIC)
 #if defined(vtkPlusOpenIGTLink_EXPORTS)
  #define vtkPlusOpenIGTLinkExport __declspec( dllexport )
 #else
  #define vtkPlusOpenIGTLinkExport __declspec( dllimport )
 #endif
#else
 #define vtkPlusOpenIGTLinkExport
#endif

#endif
