# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkIGSIOCommon vtkSequenceIO vtkVolumeReconstruction)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target vtkIGSIOCommon
add_library(vtkIGSIOCommon SHARED IMPORTED)

set_target_properties(vtkIGSIOCommon PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/IGSIO/Source/IGSIOCommon;C:/Project/PlusB-bin/IGSIO-bin/inner-build/Source/IGSIOCommon;C:/Project/PlusB-bin/IGSIO-bin/inner-build;C:/Project/PlusB-bin/IGSIO-bin/vtkAddon;C:/Project/PlusB-bin/IGSIO-bin/vtkAddon-bin"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkIOImage;vtkIOXMLParser;vtkImagingCore;vtkCommonSystem;vtkAddon;vtksys;Winmm"
)

# Create imported target vtkSequenceIO
add_library(vtkSequenceIO SHARED IMPORTED)

set_target_properties(vtkSequenceIO PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/IGSIO/Source/SequenceIO;C:/Project/PlusB-bin/IGSIO-bin/inner-build/Source/SequenceIO"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;vtkCommonDataModel;vtkIOImage;vtkIGSIOCommon;vtksys"
)

# Create imported target vtkVolumeReconstruction
add_library(vtkVolumeReconstruction SHARED IMPORTED)

set_target_properties(vtkVolumeReconstruction PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/IGSIO/Source/VolumeReconstruction;C:/Project/PlusB-bin/IGSIO-bin/inner-build/Source/VolumeReconstruction;C:/Project/PlusB-bin/IGSIO/Source/SequenceIO;C:/Project/PlusB-bin/IGSIO-bin/inner-build/Source/SequenceIO"
  INTERFACE_LINK_LIBRARIES "vtkIGSIOCommon;vtkSequenceIO"
)

# Import target "vtkIGSIOCommon" for configuration "Debug"
set_property(TARGET vtkIGSIOCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkIGSIOCommon PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/vtkIGSIOCommon.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/vtkIGSIOCommon.dll"
  )

# Import target "vtkSequenceIO" for configuration "Debug"
set_property(TARGET vtkSequenceIO APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSequenceIO PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/vtkSequenceIO.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/vtkSequenceIO.dll"
  )

# Import target "vtkVolumeReconstruction" for configuration "Debug"
set_property(TARGET vtkVolumeReconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkVolumeReconstruction PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/vtkVolumeReconstruction.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/vtkVolumeReconstruction.dll"
  )

# Import target "vtkIGSIOCommon" for configuration "Release"
set_property(TARGET vtkIGSIOCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkIGSIOCommon PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/vtkIGSIOCommon.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/vtkIGSIOCommon.dll"
  )

# Import target "vtkSequenceIO" for configuration "Release"
set_property(TARGET vtkSequenceIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSequenceIO PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/vtkSequenceIO.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/vtkSequenceIO.dll"
  )

# Import target "vtkVolumeReconstruction" for configuration "Release"
set_property(TARGET vtkVolumeReconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkVolumeReconstruction PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/vtkVolumeReconstruction.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/vtkVolumeReconstruction.dll"
  )

# Import target "vtkIGSIOCommon" for configuration "MinSizeRel"
set_property(TARGET vtkIGSIOCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkIGSIOCommon PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/vtkIGSIOCommon.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/vtkIGSIOCommon.dll"
  )

# Import target "vtkSequenceIO" for configuration "MinSizeRel"
set_property(TARGET vtkSequenceIO APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSequenceIO PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/vtkSequenceIO.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/vtkSequenceIO.dll"
  )

# Import target "vtkVolumeReconstruction" for configuration "MinSizeRel"
set_property(TARGET vtkVolumeReconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkVolumeReconstruction PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/vtkVolumeReconstruction.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/vtkVolumeReconstruction.dll"
  )

# Import target "vtkIGSIOCommon" for configuration "RelWithDebInfo"
set_property(TARGET vtkIGSIOCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkIGSIOCommon PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/vtkIGSIOCommon.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/vtkIGSIOCommon.dll"
  )

# Import target "vtkSequenceIO" for configuration "RelWithDebInfo"
set_property(TARGET vtkSequenceIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSequenceIO PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/vtkSequenceIO.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/vtkSequenceIO.dll"
  )

# Import target "vtkVolumeReconstruction" for configuration "RelWithDebInfo"
set_property(TARGET vtkVolumeReconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkVolumeReconstruction PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/vtkVolumeReconstruction.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/vtkVolumeReconstruction.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
