set(ITKCommon_LOADED 1)
set(ITKCommon_ENABLE_SHARED "1")
set(ITKCommon_DEPENDS "ITKDoubleConversion;ITKKWIML;ITKKWSys;ITKVNLInstantiation")
set(ITKCommon_PUBLIC_DEPENDS "ITKKWIML")
set(ITKCommon_TRANSITIVE_DEPENDS "ITKKWIML;ITKKWSys;ITKVNLInstantiation")
set(ITKCommon_PRIVATE_DEPENDS "ITKDoubleConversion")
set(ITKCommon_LIBRARIES "ITKCommon")
set(ITKCommon_INCLUDE_DIRS "C:/Project/PlusB-bin/itk-bin/Modules/Core/Common;C:/Project/PlusB-bin/itk/Modules/Core/Common/include")
set(ITKCommon_LIBRARY_DIRS "")
set(ITKCommon_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKCommon_TARGETS_FILE "")

