set(ITKDoubleConversion_LOADED 1)
set(ITKDoubleConversion_ENABLE_SHARED "0")
set(ITKDoubleConversion_DEPENDS "")
set(ITKDoubleConversion_PUBLIC_DEPENDS "")
set(ITKDoubleConversion_TRANSITIVE_DEPENDS "")
set(ITKDoubleConversion_PRIVATE_DEPENDS "")
set(ITKDoubleConversion_LIBRARIES "itkdouble-conversion")
set(ITKDoubleConversion_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/ThirdParty/DoubleConversion/src/double-conversion;C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/DoubleConversion/src/double-conversion")
set(ITKDoubleConversion_LIBRARY_DIRS "")
set(ITKDoubleConversion_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKDoubleConversion_TARGETS_FILE "")

