set(ITKDICOMParser_LOADED 1)
set(ITKDICOMParser_ENABLE_SHARED "0")
set(ITKDICOMParser_DEPENDS "")
set(ITKDICOMParser_PUBLIC_DEPENDS "")
set(ITKDICOMParser_TRANSITIVE_DEPENDS "")
set(ITKDICOMParser_PRIVATE_DEPENDS "")
set(ITKDICOMParser_LIBRARIES "ITKDICOMParser")
set(ITKDICOMParser_INCLUDE_DIRS "C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/DICOMParser/src/DICOMParser;C:/Project/PlusB-bin/itk/Modules/ThirdParty/DICOMParser/src/DICOMParser")
set(ITKDICOMParser_LIBRARY_DIRS "")
set(ITKDICOMParser_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKDICOMParser_TARGETS_FILE "")

