set(ITKDistanceMap_LOADED 1)
set(ITKDistanceMap_ENABLE_SHARED "0")
set(ITKDistanceMap_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel;ITKNarrowBand")
set(ITKDistanceMap_PUBLIC_DEPENDS "")
set(ITKDistanceMap_TRANSITIVE_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel;ITKNarrowBand")
set(ITKDistanceMap_PRIVATE_DEPENDS "")
set(ITKDistanceMap_LIBRARIES "ITKLabelMap;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKDistanceMap_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/DistanceMap/include")
set(ITKDistanceMap_LIBRARY_DIRS "")
set(ITKDistanceMap_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKDistanceMap_TARGETS_FILE "")

