set(ITKEigen_LOADED 1)
set(ITKEigen_ENABLE_SHARED "0")
set(ITKEigen_DEPENDS "ITKImageFilterBase")
set(ITKEigen_PUBLIC_DEPENDS "ITKImageFilterBase")
set(ITKEigen_TRANSITIVE_DEPENDS "ITKImageFilterBase")
set(ITKEigen_PRIVATE_DEPENDS "")
set(ITKEigen_LIBRARIES "ITKCommon")
set(ITKEigen_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Numerics/Eigen/include")
set(ITKEigen_LIBRARY_DIRS "")
set(ITKEigen_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKEigen_TARGETS_FILE "")

