set(ITKGPUThresholding_LOADED 1)
set(ITKGPUThresholding_ENABLE_SHARED "0")
set(ITKGPUThresholding_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUThresholding_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PRIVATE_DEPENDS "")
set(ITKGPUThresholding_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKGPUThresholding_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/GPUThresholding/include")
set(ITKGPUThresholding_LIBRARY_DIRS "")
set(ITKGPUThresholding_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKGPUThresholding_TARGETS_FILE "")

