set(ITKGDCM_LOADED 1)
set(ITKGDCM_ENABLE_SHARED "0")
set(ITKGDCM_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_PUBLIC_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_TRANSITIVE_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_PRIVATE_DEPENDS "")
set(ITKGDCM_LIBRARIES "gdcmDICT;gdcmMSFF")
set(ITKGDCM_INCLUDE_DIRS "C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/GDCM;C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/GDCM/src/gdcm/Source/Common;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/Common;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition;C:/Project/PlusB-bin/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition")
set(ITKGDCM_LIBRARY_DIRS "")
set(ITKGDCM_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKGDCM_TARGETS_FILE "")

