set(ITKImageIntensity_LOADED 1)
set(ITKImageIntensity_ENABLE_SHARED "0")
set(ITKImageIntensity_DEPENDS "ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKPath")
set(ITKImageIntensity_PUBLIC_DEPENDS "")
set(ITKImageIntensity_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKPath")
set(ITKImageIntensity_PRIVATE_DEPENDS "")
set(ITKImageIntensity_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageIntensity_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/ImageIntensity/include")
set(ITKImageIntensity_LIBRARY_DIRS "")
set(ITKImageIntensity_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKImageIntensity_TARGETS_FILE "")

