set(ITKImageSources_LOADED 1)
set(ITKImageSources_ENABLE_SHARED "0")
set(ITKImageSources_DEPENDS "ITKCommon")
set(ITKImageSources_PUBLIC_DEPENDS "")
set(ITKImageSources_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKImageSources_PRIVATE_DEPENDS "")
set(ITKImageSources_LIBRARIES "ITKCommon")
set(ITKImageSources_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/ImageSources/include")
set(ITKImageSources_LIBRARY_DIRS "")
set(ITKImageSources_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKImageSources_TARGETS_FILE "")

