set(ITKIOSpatialObjects_LOADED 1)
set(ITKIOSpatialObjects_ENABLE_SHARED "0")
set(ITKIOSpatialObjects_DEPENDS "ITKIOXML;ITKMesh;ITKSpatialObjects")
set(ITKIOSpatialObjects_PUBLIC_DEPENDS "")
set(ITKIOSpatialObjects_TRANSITIVE_DEPENDS "")
set(ITKIOSpatialObjects_PRIVATE_DEPENDS "ITKIOXML;ITKMesh;ITKSpatialObjects")
set(ITKIOSpatialObjects_LIBRARIES "ITKIOSpatialObjects")
set(ITKIOSpatialObjects_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/IO/SpatialObjects/include")
set(ITKIOSpatialObjects_LIBRARY_DIRS "")
set(ITKIOSpatialObjects_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKIOSpatialObjects_TARGETS_FILE "")

