set(ITKIOImageBase_LOADED 1)
set(ITKIOImageBase_ENABLE_SHARED "1")
set(ITKIOImageBase_DEPENDS "ITKCommon")
set(ITKIOImageBase_PUBLIC_DEPENDS "ITKCommon")
set(ITKIOImageBase_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKIOImageBase_PRIVATE_DEPENDS "")
set(ITKIOImageBase_LIBRARIES "ITKIOImageBase")
set(ITKIOImageBase_INCLUDE_DIRS "C:/Project/PlusB-bin/itk-bin/Modules/IO/ImageBase;C:/Project/PlusB-bin/itk/Modules/IO/ImageBase/include")
set(ITKIOImageBase_LIBRARY_DIRS "")
set(ITKIOImageBase_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKIOImageBase_TARGETS_FILE "")

