set(ITKIOTransformHDF5_LOADED 1)
set(ITKIOTransformHDF5_ENABLE_SHARED "1")
set(ITKIOTransformHDF5_DEPENDS "ITKHDF5;ITKIOTransformBase")
set(ITKIOTransformHDF5_PUBLIC_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformHDF5_TRANSITIVE_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformHDF5_PRIVATE_DEPENDS "ITKHDF5")
set(ITKIOTransformHDF5_LIBRARIES "ITKIOTransformHDF5")
set(ITKIOTransformHDF5_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/IO/TransformHDF5/include")
set(ITKIOTransformHDF5_LIBRARY_DIRS "")
set(ITKIOTransformHDF5_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKIOTransformHDF5_TARGETS_FILE "")

