set(ITKImageGradient_LOADED 1)
set(ITKImageGradient_ENABLE_SHARED "0")
set(ITKImageGradient_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PUBLIC_DEPENDS "")
set(ITKImageGradient_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PRIVATE_DEPENDS "")
set(ITKImageGradient_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageGradient_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/ImageGradient/include")
set(ITKImageGradient_LIBRARY_DIRS "")
set(ITKImageGradient_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKImageGradient_TARGETS_FILE "")

