set(ITKImageCompare_LOADED 1)
set(ITKImageCompare_ENABLE_SHARED "0")
set(ITKImageCompare_DEPENDS "ITKImageFilterBase;ITKImageIntensity")
set(ITKImageCompare_PUBLIC_DEPENDS "")
set(ITKImageCompare_TRANSITIVE_DEPENDS "ITKImageFilterBase;ITKImageIntensity")
set(ITKImageCompare_PRIVATE_DEPENDS "")
set(ITKImageCompare_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageCompare_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/ImageCompare/include")
set(ITKImageCompare_LIBRARY_DIRS "")
set(ITKImageCompare_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKImageCompare_TARGETS_FILE "")

