set(ITKLabelVoting_LOADED 1)
set(ITKLabelVoting_ENABLE_SHARED "0")
set(ITKLabelVoting_DEPENDS "ITKThresholding")
set(ITKLabelVoting_PUBLIC_DEPENDS "ITKThresholding")
set(ITKLabelVoting_TRANSITIVE_DEPENDS "ITKThresholding")
set(ITKLabelVoting_PRIVATE_DEPENDS "")
set(ITKLabelVoting_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKLabelVoting_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Segmentation/LabelVoting/include")
set(ITKLabelVoting_LIBRARY_DIRS "")
set(ITKLabelVoting_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKLabelVoting_TARGETS_FILE "")

