set(ITKMarkovRandomFieldsClassifiers_LOADED 1)
set(ITKMarkovRandomFieldsClassifiers_ENABLE_SHARED "0")
set(ITKMarkovRandomFieldsClassifiers_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_PUBLIC_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_TRANSITIVE_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_PRIVATE_DEPENDS "")
set(ITKMarkovRandomFieldsClassifiers_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKMarkovRandomFieldsClassifiers_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Segmentation/MarkovRandomFieldsClassifiers/include")
set(ITKMarkovRandomFieldsClassifiers_LIBRARY_DIRS "")
set(ITKMarkovRandomFieldsClassifiers_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKMarkovRandomFieldsClassifiers_TARGETS_FILE "")

