set(ITKQuadEdgeMesh_LOADED 1)
set(ITKQuadEdgeMesh_ENABLE_SHARED "1")
set(ITKQuadEdgeMesh_DEPENDS "ITKCommon;ITKMesh")
set(ITKQuadEdgeMesh_PUBLIC_DEPENDS "")
set(ITKQuadEdgeMesh_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKQuadEdgeMesh_PRIVATE_DEPENDS "ITKMesh")
set(ITKQuadEdgeMesh_LIBRARIES "ITKQuadEdgeMesh")
set(ITKQuadEdgeMesh_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Core/QuadEdgeMesh/include")
set(ITKQuadEdgeMesh_LIBRARY_DIRS "")
set(ITKQuadEdgeMesh_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKQuadEdgeMesh_TARGETS_FILE "")

