set(ITKSmoothing_LOADED 1)
set(ITKSmoothing_ENABLE_SHARED "0")
set(ITKSmoothing_DEPENDS "ITKImageFunction")
set(ITKSmoothing_PUBLIC_DEPENDS "")
set(ITKSmoothing_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKSmoothing_PRIVATE_DEPENDS "")
set(ITKSmoothing_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKSmoothing_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/Smoothing/include")
set(ITKSmoothing_LIBRARY_DIRS "")
set(ITKSmoothing_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKSmoothing_TARGETS_FILE "")

