set(ITKSpatialFunction_LOADED 1)
set(ITKSpatialFunction_ENABLE_SHARED "0")
set(ITKSpatialFunction_DEPENDS "ITKImageFunction")
set(ITKSpatialFunction_PUBLIC_DEPENDS "")
set(ITKSpatialFunction_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKSpatialFunction_PRIVATE_DEPENDS "")
set(ITKSpatialFunction_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKSpatialFunction_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Filtering/SpatialFunction/include")
set(ITKSpatialFunction_LIBRARY_DIRS "")
set(ITKSpatialFunction_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKSpatialFunction_TARGETS_FILE "")

