set(ITKVideoFiltering_LOADED 1)
set(ITKVideoFiltering_ENABLE_SHARED "0")
set(ITKVideoFiltering_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_PUBLIC_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_TRANSITIVE_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_PRIVATE_DEPENDS "")
set(ITKVideoFiltering_LIBRARIES "ITKVideoCore")
set(ITKVideoFiltering_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/Video/Filtering/include")
set(ITKVideoFiltering_LIBRARY_DIRS "")
set(ITKVideoFiltering_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKVideoFiltering_TARGETS_FILE "")

