set(ITKVNL_LOADED 1)
set(ITKVNL_ENABLE_SHARED "0")
set(ITKVNL_DEPENDS "")
set(ITKVNL_PUBLIC_DEPENDS "")
set(ITKVNL_TRANSITIVE_DEPENDS "")
set(ITKVNL_PRIVATE_DEPENDS "")
set(ITKVNL_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl")
set(ITKVNL_INCLUDE_DIRS "C:/Project/PlusB-bin/itk/Modules/ThirdParty/VNL/src/vxl/v3p/netlib;C:/Project/PlusB-bin/itk/Modules/ThirdParty/VNL/src/vxl/vcl;C:/Project/PlusB-bin/itk/Modules/ThirdParty/VNL/src/vxl/core;C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/VNL/src/vxl/v3p/netlib;C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/VNL/src/vxl/vcl;C:/Project/PlusB-bin/itk-bin/Modules/ThirdParty/VNL/src/vxl/core")
set(ITKVNL_LIBRARY_DIRS "")
set(ITKVNL_RUNTIME_LIBRARY_DIRS "C:/Project/PlusB-bin/bin")
set(ITKVNL_TARGETS_FILE "")

