# CMake generated Testfile for 
# Source directory: C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing
# Build directory: C:/Project/PlusB-bin/PlusLib-bin/src/PlusDataCollection/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TimestampFilteringTest "C:/Project/PlusB-bin/bin/TimestampFilteringTest" "--source-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/TimestampFilteringTest.igs.mha" "--averaged-items-for-filtering=20" "--max-timestamp-difference=0.08" "--min-stdev-reduction-factor=3.0" "--transform=IdentityToIdentityTransform")
set_tests_properties(TimestampFilteringTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;17;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkDataCollectorTest1 "C:/Project/PlusB-bin/bin/vtkDataCollectorTest1" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_DataCollectionOnly_SavedDataset.xml" "--video-buffer-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/WaterTankBottomTranslationVideoBuffer.igs.mha" "--tracker-buffer-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/WaterTankBottomTranslationTrackerBuffer-trimmed.igs.mha" "--rendering-off")
set_tests_properties(vtkDataCollectorTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;32;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkDataCollectorTest2 "C:/Project/PlusB-bin/bin/vtkDataCollectorTest2" "--video-buffer-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/WaterTankBottomTranslationVideoBuffer.igs.mha" "--tracker-buffer-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/WaterTankBottomTranslationTrackerBuffer-trimmed.igs.mha" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_DataCollectionOnly_SavedDataset.xml" "--acq-time-length=5" "--verbose=3")
set_tests_properties(vtkDataCollectorTest2 PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;55;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtk3DDataCollectorTest1 "C:/Project/PlusB-bin/bin/vtk3DDataCollectorTest1" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_DataCollectionOnly_3DSavedDataset.xml" "--minimum=0" "--maximum=253" "--mean=8.08658" "--median=0" "--standard-deviation=21.6785" "--xDimension=112" "--yDimension=112" "--zDimension=48" "--verbose=3")
set_tests_properties(vtk3DDataCollectorTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;69;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(ReplayRecordedDataTest "C:/Project/PlusB-bin/bin/ReplayRecordedDataTest" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_OpenIGTLinkTestServer.xml")
set_tests_properties(ReplayRecordedDataTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;101;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkDataCollectorFileTest "C:/Project/PlusB-bin/bin/vtkDataCollectorFileTest" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_DataCollectionOnly_File.xml")
set_tests_properties(vtkDataCollectorFileTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;111;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(PlusVersion "C:/Project/PlusB-bin/bin/PlusVersion")
set_tests_properties(PlusVersion PROPERTIES  _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;119;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkMetaImageSequenceIOTest "C:/Project/PlusB-bin/bin/vtkMetaImageSequenceIOTest" "--img-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/MetaImageSequenceIOTest1.igs.mhd" "--output-img-seq-file=MetaImageSequenceIOTest1Output.igs.mha")
set_tests_properties(vtkMetaImageSequenceIOTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;128;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(ViewSequenceFileTest "C:/Project/PlusB-bin/bin/ViewSequenceFile" "--source-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/SpinePhantomFreehand.igs.mha" "--config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_SpinePhantomFreehandReconstructionOnly.xml" "--image-to-reference-transform=ImageToTracker" "--rendering-off")
set_tests_properties(ViewSequenceFileTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;137;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkFcsvReaderTest1 "C:/Project/PlusB-bin/bin/vtkFcsvReaderTest1" "C:/Project/PlusB-bin/PlusLibData/TestImages/FcsvReaderTest1.fcsv")
set_tests_properties(vtkFcsvReaderTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;151;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkFcsvWriterTest1 "C:/Project/PlusB-bin/bin/vtkFcsvWriterTest1" "C:/Project/PlusB-bin/PlusLibData/TestImages/FcsvReaderTest1.fcsv" "C:/Project/PlusB-bin/PlusLib-bin/src/PlusDataCollection/Testing/FcsvWriterTest1.fcsv")
set_tests_properties(vtkFcsvWriterTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;160;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkOpenIGTLinkTrackerTest "C:/Project/PlusB-bin/bin/vtkOpenIGTLinkTrackerTest" "--client-config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_OpenIGTLinkTracker_TDATA_Client.xml" "--server-config-file=C:/Project/PlusB-bin/PlusLibData/ConfigFiles/Testing/PlusDeviceSet_OpenIGTLinkTracker_TDATA_Server.xml")
set_tests_properties(vtkOpenIGTLinkTrackerTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;477;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(vtkPlusDeviceFactoryTest "C:/Project/PlusB-bin/bin/vtkPlusDeviceFactoryTest")
set_tests_properties(vtkPlusDeviceFactoryTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;516;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
add_test(TransformInterpolationTest "C:/Project/PlusB-bin/bin/TransformInterpolationTest" "--source-seq-file=C:/Project/PlusB-bin/PlusLibData/TestImages/TransformInterpolationTest.igs.mha" "--transform=ProbeToTracker" "--max-rotation-difference=1.0" "--max-translation-difference=0.5")
set_tests_properties(TransformInterpolationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;554;ADD_TEST;C:/Project/PlusB-bin/PlusLib/src/PlusDataCollection/Testing/CMakeLists.txt;0;")
