# - Config file for the PlusApp package
# It defines the following variables
#  PlusApp_INCLUDE_DIRS - include directories for PlusApp
#  PlusApp_LIBRARY_DIRS - library directories for PlusApp (normally not used!)
#  PlusApp_LIRARIES - list of targets exported by this package

# Resolve needed dependencies
SET(Qt5_DIR C:/Qt/Qt5.7.1/5.7/msvc2015_64/lib/cmake/Qt5)
FIND_PACKAGE(Qt5 REQUIRED COMPONENTS Core;Widgets;Test;Xml;Core;Gui;Network;Sql;XmlPatterns;OpenGL;Test;Widgets;Xml)
SET(PlusLib_DIR C:/Project/PlusB-bin/PlusLib-bin)
FIND_PACKAGE(PlusLib REQUIRED PATHS "${PlusLib_DIR}/src" NO_MODULE)

# Tell the user project where to find our headers and libraries
SET(PlusApp_INCLUDE_DIRS "C:/Project/PlusB-bin/PlusApp;C:/Project/PlusB-bin/PlusApp-bin")
SET(PlusApp_LIBRARY_DIRS "")
SET(PlusApp_LIBRARIES "")

# Tell the user project where to find PlusApp use file
SET(PlusApp_USE_FILE "C:/Project/PlusB-bin/PlusApp-bin/UsePlusApp.cmake" )
 
# Include targets generated by PlusApp (contains definitions for IMPORTED targets)
include("C:/Project/PlusB-bin/PlusApp-bin/PlusAppLibraryTargets.cmake")

