/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkPlusServerExport - manage Windows system differences
// .SECTION Description
// The __vtkPlusServerExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkPlusServerExport_h
#define __vtkPlusServerExport_h

#if defined(WIN32) && !defined(PlusLib_STATIC)
 #if defined(vtkPlusServer_EXPORTS)
  #define vtkPlusServerExport __declspec( dllexport )
 #else
  #define vtkPlusServerExport __declspec( dllimport )
 #endif
#else
 #define vtkPlusServerExport
#endif

#endif
