
#ifndef VTKVOLUMERECONSTRUCTION_EXPORT_H
#define VTKVOLUMERECONSTRUCTION_EXPORT_H

#ifdef VTKVOLUMERECONSTRUCTION_STATIC_DEFINE
#  define VTKVOLUMERECONSTRUCTION_EXPORT
#  define VTKVOLUMERECONSTRUCTION_NO_EXPORT
#else
#  ifndef VTKVOLUMERECONSTRUCTION_EXPORT
#    ifdef vtkVolumeReconstruction_EXPORTS
        /* We are building this library */
#      define VTKVOLUMERECONSTRUCTION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKVOLUMERECONSTRUCTION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKVOLUMERECONSTRUCTION_NO_EXPORT
#    define VTKVOLUMERECONSTRUCTION_NO_EXPORT 
#  endif
#endif

#ifndef VTKVOLUMERECONSTRUCTION_DEPRECATED
#  define VTKVOLUMERECONSTRUCTION_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKVOLUMERECONSTRUCTION_DEPRECATED_EXPORT
#  define VTKVOLUMERECONSTRUCTION_DEPRECATED_EXPORT VTKVOLUMERECONSTRUCTION_EXPORT VTKVOLUMERECONSTRUCTION_DEPRECATED
#endif

#ifndef VTKVOLUMERECONSTRUCTION_DEPRECATED_NO_EXPORT
#  define VTKVOLUMERECONSTRUCTION_DEPRECATED_NO_EXPORT VTKVOLUMERECONSTRUCTION_NO_EXPORT VTKVOLUMERECONSTRUCTION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKVOLUMERECONSTRUCTION_NO_DEPRECATED
#    define VTKVOLUMERECONSTRUCTION_NO_DEPRECATED
#  endif
#endif

#endif /* VTKVOLUMERECONSTRUCTION_EXPORT_H */
