# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget igtlioLogic igtlioDevices igtlioConverter igtlioTools)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target igtlioLogic
add_library(igtlioLogic SHARED IMPORTED)

set_target_properties(igtlioLogic PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/OpenIGTLinkIO/Logic;C:/Project/PlusB-bin/OpenIGTLinkIO-bin/Logic"
  INTERFACE_LINK_LIBRARIES "igtlioDevices;OpenIGTLink;vtkCommonSystem;vtkIOImage;vtkCommonCore;vtksys;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkCommonExecutionModel;vtkDICOMParser;vtkmetaio;vtkzlib;vtkjpeg;vtkpng;vtktiff;vtkImagingMath"
)

# Create imported target igtlioDevices
add_library(igtlioDevices SHARED IMPORTED)

set_target_properties(igtlioDevices PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/OpenIGTLinkIO/Devices;C:/Project/PlusB-bin/OpenIGTLinkIO-bin/Devices"
  INTERFACE_LINK_LIBRARIES "igtlioConverter;OpenIGTLink;vtkCommonSystem;vtkCommonCore;vtksys;vtkIOImage;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonTransforms;vtkCommonExecutionModel;vtkDICOMParser;vtkmetaio;vtkzlib;vtkjpeg;vtkpng;vtktiff;vtkImagingMath"
)

# Create imported target igtlioConverter
add_library(igtlioConverter SHARED IMPORTED)

set_target_properties(igtlioConverter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/OpenIGTLinkIO/Converter;C:/Project/PlusB-bin/OpenIGTLinkIO-bin/Converter"
  INTERFACE_LINK_LIBRARIES "OpenIGTLink;vtkIOImage;vtkCommonCore;vtksys;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkCommonExecutionModel;vtkDICOMParser;vtkmetaio;vtkzlib;vtkjpeg;vtkpng;vtktiff;vtkImagingMath"
)

# Create imported target igtlioTools
add_library(igtlioTools SHARED IMPORTED)

set_target_properties(igtlioTools PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Project/PlusB-bin/OpenIGTLinkIO/Tools;C:/Project/PlusB-bin/OpenIGTLinkIO-bin/Tools"
  INTERFACE_LINK_LIBRARIES "OpenIGTLink;vtkIOXMLParser;vtkCommonCore;vtksys;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkIOCore;vtkCommonExecutionModel;vtkdoubleconversion;vtklz4;vtklzma;vtkzlib;vtkexpat"
)

# Import target "igtlioLogic" for configuration "Debug"
set_property(TARGET igtlioLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(igtlioLogic PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/igtlioLogic.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/igtlioLogic.dll"
  )

# Import target "igtlioDevices" for configuration "Debug"
set_property(TARGET igtlioDevices APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(igtlioDevices PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/igtlioDevices.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/igtlioDevices.dll"
  )

# Import target "igtlioConverter" for configuration "Debug"
set_property(TARGET igtlioConverter APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(igtlioConverter PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/igtlioConverter.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/igtlioConverter.dll"
  )

# Import target "igtlioTools" for configuration "Debug"
set_property(TARGET igtlioTools APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(igtlioTools PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Project/PlusB-bin/lib/Debug/igtlioTools.lib"
  IMPORTED_LOCATION_DEBUG "C:/Project/PlusB-bin/bin/Debug/igtlioTools.dll"
  )

# Import target "igtlioLogic" for configuration "Release"
set_property(TARGET igtlioLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igtlioLogic PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/igtlioLogic.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/igtlioLogic.dll"
  )

# Import target "igtlioDevices" for configuration "Release"
set_property(TARGET igtlioDevices APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igtlioDevices PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/igtlioDevices.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/igtlioDevices.dll"
  )

# Import target "igtlioConverter" for configuration "Release"
set_property(TARGET igtlioConverter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igtlioConverter PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/igtlioConverter.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/igtlioConverter.dll"
  )

# Import target "igtlioTools" for configuration "Release"
set_property(TARGET igtlioTools APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igtlioTools PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Project/PlusB-bin/lib/Release/igtlioTools.lib"
  IMPORTED_LOCATION_RELEASE "C:/Project/PlusB-bin/bin/Release/igtlioTools.dll"
  )

# Import target "igtlioLogic" for configuration "MinSizeRel"
set_property(TARGET igtlioLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(igtlioLogic PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/igtlioLogic.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/igtlioLogic.dll"
  )

# Import target "igtlioDevices" for configuration "MinSizeRel"
set_property(TARGET igtlioDevices APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(igtlioDevices PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/igtlioDevices.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/igtlioDevices.dll"
  )

# Import target "igtlioConverter" for configuration "MinSizeRel"
set_property(TARGET igtlioConverter APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(igtlioConverter PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/igtlioConverter.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/igtlioConverter.dll"
  )

# Import target "igtlioTools" for configuration "MinSizeRel"
set_property(TARGET igtlioTools APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(igtlioTools PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Project/PlusB-bin/lib/MinSizeRel/igtlioTools.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Project/PlusB-bin/bin/MinSizeRel/igtlioTools.dll"
  )

# Import target "igtlioLogic" for configuration "RelWithDebInfo"
set_property(TARGET igtlioLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(igtlioLogic PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/igtlioLogic.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/igtlioLogic.dll"
  )

# Import target "igtlioDevices" for configuration "RelWithDebInfo"
set_property(TARGET igtlioDevices APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(igtlioDevices PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/igtlioDevices.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/igtlioDevices.dll"
  )

# Import target "igtlioConverter" for configuration "RelWithDebInfo"
set_property(TARGET igtlioConverter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(igtlioConverter PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/igtlioConverter.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/igtlioConverter.dll"
  )

# Import target "igtlioTools" for configuration "RelWithDebInfo"
set_property(TARGET igtlioTools APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(igtlioTools PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Project/PlusB-bin/lib/RelWithDebInfo/igtlioTools.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Project/PlusB-bin/bin/RelWithDebInfo/igtlioTools.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
